# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Hot Forging', kernelModule='MacroHotForging', kernelFunction='MacroHotForging', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgTabBook(name='TabBook_3', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_5', p='TabBook_3', text='Step 1: Basic data.')
RsgGroupBox(name='GroupBox_5', p='TabItem_5', text='Sample dimensions:', layout='0')
RsgTextField(p='GroupBox_5', fieldType='Float', ncols=7, labelText='Radius [mm]:', keyword='radius', default='50')
RsgTextField(p='GroupBox_5', fieldType='Float', ncols=7, labelText='Length [mm]:', keyword='length', default='150')
RsgIcon(p='GroupBox_5', fileName=r'Preview.PNG')
RsgGroupBox(name='GroupBox_8', p='TabItem_5', text='Sample temperature:', layout='0')
RsgSpinner(p='GroupBox_8', text='[\xb0C]:', ncols=12, valueType=FLOAT, increment=1.0, minValue=-40, maxValue=40, keyword='sampleTemperature', default=19)
RsgGroupBox(name='GroupBox_9', p='TabItem_5', text='Tool temperature:', layout='0')
RsgSpinner(p='GroupBox_9', text='[\xb0C]:', ncols=12, valueType=FLOAT, increment=1.0, minValue=-40, maxValue=40, keyword='toolTemperature', default=19)
RsgTabItem(name='TabItem_6', p='TabBook_3', text='Step 2: Data for forging.')
RsgGroupBox(name='GroupBox_6', p='TabItem_6', text='Emissivity coefficient for steel [e]:', layout='0')
RsgIcon(p='GroupBox_6', fileName=r'Emissivity Coefficient for Steel.PNG')
RsgSlider(p='GroupBox_6', text='Set', minLabelText='Min', maxLabelText='Max', valueType=FLOAT, minValue=0.07, maxValue=0.88, decimalPlaces=2, showValue=True, width=380, keyword='emissivity', default=0.88)
RsgGroupBox(name='GroupBox_7', p='TabItem_6', text='Melting point [\xb0C]:', layout='0')
RsgIcon(p='GroupBox_7', fileName=r'Melting Point for Steel.PNG')
RsgSlider(p='GroupBox_7', text='Set', minLabelText='Min', maxLabelText='Max', valueType=INTEGER, minValue=1425, maxValue=1540, decimalPlaces=1, showValue=True, width=380, keyword='meltingpoint', default=1430)
RsgGroupBox(name='GroupBox_10', p='TabItem_6', text='Sample deformation', layout='0')
RsgSpinner(p='GroupBox_10', text='-[mm]:', ncols=6, valueType=FLOAT, increment=1.0, minValue=1, maxValue=10000000, keyword='sampleDeformation', default=30)
dialogBox.show()